In [16]:
# Task 0

def inplace_add_vectors (A : list, B : list):
    if len(A) == len(B):
        for i in range (len(A)):
            A[i] = A[i] + B[i]
    else:
        print('Indexes do no match')
A = [ i for i in range(1,4) ]
B = [ i for i in range(3,6) ]
inplace_add_vectors(A,B)

def add_vectors (A : list, B : list):
    C = A.copy()
    if len(A) == len(B):
        for i in range (len(A)):
            C[i] = A[i] + B[i]
    else:
        print('Indexes do no match')
    return C
C = add_vectors(A,B)
print(C)



[7, 10, 13]


In [36]:
# Task 1

import numpy as np
shape = (500, 500)
matrix = np.random.randint(0,100,shape)

def mean(matrix):
    sum = 0
    size = shape[0]*shape[1]
    for row in matrix:
        for col in row:
             sum += col
    return sum/size

def sum(matrix):
    sum = 0
    for row in matrix:
        for col in row:
             sum += col
    return sum

def multiply(matrix,val):
    multiplyMatrix = matrix.copy()
    for i,row in enumerate(matrix):
        for j,col in enumerate(row):
            multiplyMatrix[i][j] = col*val
    return multiplyMatrix

def variance(matrix):
    sum = 0
    meanVal = mean(matrix)
    for row in matrix:
        for col in row:
            sum += (col - meanVal)**2
    return (sum/shape[0]**2)

print(mean(matrix))
print(sum(matrix))
print(multiply(matrix,10))
print(variance(matrix))

49.606296
12401574
[[200 660 870 ... 820  90 400]
 [380 710 250 ... 240 130 390]
 [150 650 800 ...  80 420 860]
 ...
 [810 880  80 ... 260   0 640]
 [400 950 680 ... 790  30 790]
 [520 290 740 ... 860 620 370]]
835.5897011604322


In [105]:
# Task 2

import numpy as np
shape = (50,50)
matrix = [[ 0 for i in range(shape[0]) ] for j in range(shape[1])]
for i in range (shape[0]):
    for j in range (shape[1]):
        if i == j:
            matrix[i][j] = -2
        elif i-1 == j or i+1 == j:
            matrix[i][j] = 1
        else:
            matrix[i][j] = 0
matrix = np.asarray(matrix)
vector = np.random.rand(shape[0])

for i in range (100):
    vector = np.dot(matrix,vector)/np.linalg.norm(vector)

vectorT = np.transpose(vector)
eigenValue = np.dot(vectorT, np.dot(matrix, vector))/np.dot(vectorT, vector)

Lambda, V = np.linalg.eig(matrix)
print(eigenValue)
print(max(abs(Lambda)))

-3.983513571511639
3.996206657474088


In [ ]:
# Task 3

